packages:
  - 'packages/*'

catalog:
  '@changesets/changelog-github': ^0.6.0
  '@changesets/cli': ^2.30.0
  '@commitlint/cli': ^20.5.0
  '@commitlint/types': ^20.5.0
  browserslist: ^4.25.3
  eslint: ^10.0.0
  lefthook: ^2.1.4
  prettier: ^3.8.1
  stylelint: ^17.4.0
  turbo: ^2.8.17
