import eslintPluginJsdoc from 'eslint-plugin-jsdoc';

import { JS_FILES, TS_FILES } from '../lib/file-patterns.js';

/** @import { Linter } from 'eslint' */

/** @type {Linter.Config} */
const baseConfig = {
  plugins: {
    jsdoc: eslintPluginJsdoc,
  },
};

// Compose the plugin's per-category presets — `contents` (valid tag content),
// `logical` (sound tags), and `stylistic` (consistent formatting) — rather than
// the `recommended-*` bundle. These enforce JSDoc *quality* without mandating
// that JSDoc *exist*; the `requirements` category (the "tags must exist" set)
// is an opt-in export (`./plugins/jsdoc-required`). The JS-vs-TS flavor split
// mirrors the bundle: TS files reject inline types, JS files keep them.
//
// Caveat: the granular category presets are generated by one factory that emits
// each category's rules at a uniform severity with no flavor-specific overrides
// — so `*-typescript` and `*-typescript-flavor` are identical, and the
// type-system tunings that the `recommended-*` bundles hand-apply are lost. We
// restore those tunings below so each flavor matches its `recommended-*` bundle.

/** @type {Linter.Config} */
export const jsConfig = {
  files: [...JS_FILES],
  ...baseConfig,
  rules: {
    ...eslintPluginJsdoc.configs['flat/contents-typescript-flavor-error'].rules,
    ...eslintPluginJsdoc.configs['flat/logical-typescript-flavor-error'].rules,
    ...eslintPluginJsdoc.configs['flat/stylistic-typescript-flavor-error'].rules,
    // JS files use JSDoc as their type source. The `logical` category enables
    // `no-types` and `no-undefined-types`; the `recommended-typescript-flavor`
    // bundle disables both. Restore that: permit inline types (else the split
    // collapses and the `./plugins/jsdoc-required` opt-in's `require-*-type`
    // rules become unsatisfiable), and don't flag references to global,
    // cross-file, or `@import`ed types as undefined.
    'jsdoc/no-types': 'off',
    'jsdoc/no-undefined-types': 'off',
    // The `contents` category enables `text-escaping` at error; every
    // `recommended-*` bundle ships it off. Restore that: its autofix escapes
    // `<` -> `&lt;` in JSDoc but isn't markdown-aware (it mangles `<` inside
    // backtick code spans) and escapes only `<`, not `>` (asymmetric garbage).
    // It targets JSDoc rendered as raw HTML; TS/TSDoc and editor hover render
    // markdown, so the escaping is pure corruption there.
    'jsdoc/text-escaping': 'off',
  },
};

/** @type {Linter.Config} */
export const tsConfig = {
  files: [...TS_FILES],
  ...baseConfig,
  rules: {
    ...eslintPluginJsdoc.configs['flat/contents-typescript-error'].rules,
    ...eslintPluginJsdoc.configs['flat/logical-typescript-error'].rules,
    ...eslintPluginJsdoc.configs['flat/stylistic-typescript-error'].rules,
    // Match the `recommended-typescript` bundle's tunings that the `logical`
    // category drops: TS itself validates type references, so the JSDoc
    // `no-undefined-types` check is redundant and false-positive-prone, and
    // `check-tag-names` should run in typed mode.
    'jsdoc/no-undefined-types': 'off',
    'jsdoc/check-tag-names': ['error', { typed: true }],
    // See `jsConfig` above: the `contents` category re-enables `text-escaping`
    // that every `recommended-*` bundle ships off; its non-markdown-aware
    // autofix corrupts `<` inside code spans. Restore the bundle default.
    'jsdoc/text-escaping': 'off',
  },
};
