name: Release

on:
  workflow_run:
    # Must match the 'name' field in ci.yml exactly
    workflows: ['CI']
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  attestations: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    name: Release
    uses: benhigham/.github/.github/workflows/release-changesets.yml@c2ed5ffe83a6558a8d75e8b158240a0b8daee1a9 # main (pinned 2026-03-26)
