name: Release

on:
  workflow_run:
    # Must match the 'name' field in ci.yml exactly
    workflows: ['CI']
    branches: [main]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  attestations: write
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    name: Release
    uses: benhigham/.github/.github/workflows/release-changesets.yml@7bc8cef99349404fd87f3a027cc35a71cf0f0aec # main (pinned 2026-03-26)
